export const consultationTypes = {
  FETCH_CONSULTATION_SUCCESS: 'FETCH_CONSULTATION_SUCCESS',
  FETCH_CONSULTATION_LIST_SUCCESS: 'FETCH_CONSULTATION_LIST_SUCCESS',
};

export const consultationPostTypes = {
  FETCH_CONSULTATION_POSTS_SUCCESS: 'FETCH_CONSULTATION_POSTS_SUCCESS',
};

export const loginErrorTypes = {
  SET_LOGIN_ERROR: 'SET_LOGIN_ERROR',
  FLUSH_LOGIN_ERROR: 'FLUSH_LOGIN_ERROR',
};
