export const mommiesTypes = {
  FETCH_MOMMIES: 'FETCH_MOMMIES',
  FETCH_MOMMIES_SUCCESS: 'FETCH_MOMMIES_SUCCESS',
  FETCH_MOMMIES_FAILURE: 'FETCH_MOMMIES_FAILURE',
};

export const cadresTypes = {
  FETCH_CADRES: 'FETCH_CADRES',
  FETCH_CADRES_SUCCESS: 'FETCH_CADRES_SUCCESS',
  FETCH_CADRES_FAILURE: 'FETCH_CADRES_FAILURE',
};

export const midwifesTypes = {
  FETCH_MIDWIFES: 'FETCH_MIDWIFES',
  FETCH_MIDWIFES_SUCCESS: 'FETCH_MIDWIFES_SUCCESS',
  FETCH_MIDWIFES_FAILURE: 'FETCH_MIDWIFES_FAILURE',
};

export const conselorsTypes = {
  FETCH_CONSELORS: 'FETCH_CONSELORS',
  FETCH_CONSELORS_SUCCESS: 'FETCH_CONSELORS_SUCCESS',
  FETCH_CONSELORS_FAILURE: 'FETCH_CONSELORS_FAILURE',
};

export const doctorGeneralTypes = {
  FETCH_DOCTOR_GENERAL: 'FETCH_DOCTOR_GENERAL',
  FETCH_DOCTOR_GENERAL_SUCCESS: 'FETCH_DOCTOR_GENERAL_SUCCESS',
  FETCH_DOCTOR_GENERAL_FAILURE: 'FETCH_DOCTOR_GENERAL_FAILURE',
};

export const doctorSpecialistTypes = {
  FETCH_DOCTOR_SPECIALIST: 'FETCH_DOCTOR_SPECIALIST',
  FETCH_DOCTOR_SPECIALIST_SUCCESS: 'FETCH_DOCTOR_SPECIALIST_SUCCESS',
  FETCH_DOCTOR_SPECIALIST_FAILURE: 'FETCH_DOCTOR_SPECIALIST_FAILURE',
};

export const administratorTypes = {
  FETCH_ADMINISTRATOR: 'FETCH_ADMINISTRATOR',
  FETCH_ADMINISTRATOR_SUCCESS: 'FETCH_ADMINISTRATOR_SUCCESS',
  FETCH_ADMINISTRATOR_FAILURE: 'FETCH_ADMINISTRATOR_FAILURE',
};
