export default {
  FETCH_ARTICLE_CATEGORIES: 'FETCH_ARTICLE_CATEGORIES',
  FETCH_ARTICLE_CATEGORIES_SUCCESS: 'FETCH_ARTICLE_CATEGORIES_SUCCESS',
  FETCH_ARTICLE_CATEGORIES_FAILURE: 'FETCH_ARTICLE_CATEGORIES_FAILURE',
};
