export const villagesTypes = {
  FETCH_VILLAGES: 'FETCH_VILLAGES',
  FETCH_VILLAGES_SUCCESS: 'FETCH_VILLAGES_SUCCESS',
  FETCH_VILLAGES_FAILURE: 'FETCH_VILLAGES_FAILURE',
};

export const subDistrictsTypes = {
  FETCH_SUB_DISTRICTS: 'FETCH_SUB_DISTRICTS',
  FETCH_SUB_DISTRICTS_SUCCESS: 'FETCH_SUB_DISTRICTS_SUCCESS',
  FETCH_SUB_DISTRICTS_FAILURE: 'FETCH_SUB_DISTRICTS_FAILURE',
};

export const districtsTypes = {
  FETCH_DISTRICTS: 'FETCH_DISTRICTS',
  FETCH_DISTRICTS_SUCCESS: 'FETCH_DISTRICTS_SUCCESS',
  FETCH_DISTRICTS_FAILURE: 'FETCH_DISTRICTS_FAILURE',
};

export const provincesTypes = {
  FETCH_PROVINCES: 'FETCH_PROVINCES',
  FETCH_PROVINCES_SUCCESS: 'FETCH_PROVINCES_SUCCESS',
  FETCH_PROVINCES_FAILURE: 'FETCH_PROVINCES_FAILURE',
};
