export default {
  SET_SESSION: 'SET_SESSION',
  FLUSH_SESSION: 'FLUSH_SESSION',
  FETCH_LOGIN: 'FETCH_LOGIN',
  FETCH_LOGIN_SUCCESS: 'FETCH_LOGIN_SUCCESS',
  FETCH_LOGIN_FAILURE: 'FETCH_LOGIN_FAILURE',
};
